:runner:
  :default:
    :backend:
      :redis:
        :jobs:
          :url: redis://localhost:6379/1
        :tutoriel:
          :url: redis://localhost:6379/2

  :development:
    :application:
      :name: Tutoriel Sidekiq
